-- liquibase formatted sql

-- changeset nicoletti:1734468468510-1
CREATE TABLE "tb_apostas" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "conferido" BOOLEAN, "data_aposta" TIMESTAMP WITHOUT TIME ZONE, "numero_concurso" INTEGER, "premiado" BOOLEAN, "quantidade_acerto" INTEGER, "quantidade_numero_apostado" INTEGER, "valor_aposta" numeric(19, 2), "valor_premio" numeric(19, 2), "tipo_jogo_id" BIGINT, CONSTRAINT "tb_apostas_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-2
CREATE TABLE "tb_dezenas" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "acerto" BOOLEAN, "dezena" INTEGER, "aposta_id" BIGINT, CONSTRAINT "tb_dezenas_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-3
CREATE TABLE "tb_dezenas_jogos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 65899) NOT NULL, "dezena" INTEGER, "ordem" INTEGER, "jogo_id" BIGINT, CONSTRAINT "tb_dezenas_jogos_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-4
CREATE TABLE "tb_erro_loto" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "detalhes" TEXT, "numero_concurso" INTEGER, "tipo_jogo" VARCHAR(255), "ultima_tentativa" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "tb_erro_loto_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-5
CREATE TABLE "tb_jogos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6079) NOT NULL, "acumulado" BOOLEAN, "data_apuracao" TIMESTAMP WITHOUT TIME ZONE, "local_sorteio" VARCHAR(255), "numero_concurso" INTEGER, "numero_concurso_anterior" INTEGER, "numero_concurso_proximo" INTEGER, "valor_acumulado_proximo_concurso" numeric(19, 2), "valor_arrecadado" numeric(19, 2), "valor_estimado_proximo_concurso" numeric(19, 2), "tipo_jogo_id" BIGINT, CONSTRAINT "tb_jogos_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-6
CREATE TABLE "tb_premios" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 24775) NOT NULL, "descricao" VARCHAR(255), "faixa" INTEGER, "numero_ganhadores" INTEGER, "valor_premio" numeric(19, 2), "jogo_id" BIGINT, CONSTRAINT "tb_premios_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-7
CREATE TABLE "tb_tipos_jogo" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL, "nome" VARCHAR(255) NOT NULL, "quantidade_numeros_disponiveis" INTEGER, "quantidade_numeros_maximo" INTEGER, "quantidade_numeros_maximo_para_ganhar" INTEGER, "quantidade_numeros_minimo" INTEGER, "quantidade_numeros_minimo_para_ganhar" INTEGER, CONSTRAINT "tb_tipos_jogo_pkey" PRIMARY KEY ("id"));

-- changeset nicoletti:1734468468510-8
ALTER TABLE "tb_tipos_jogo" ADD CONSTRAINT "uk_d7dho1ovide1juxxcwsh0a101" UNIQUE ("nome");

-- changeset nicoletti:1734468468510-9
ALTER TABLE "tb_apostas" ADD CONSTRAINT "fk79wc7uq7p96yfi7e82w79rpo9" FOREIGN KEY ("tipo_jogo_id") REFERENCES "tb_tipos_jogo" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset nicoletti:1734468468510-10
ALTER TABLE "tb_jogos" ADD CONSTRAINT "fkekpid2n56n7c64lqu9674qj65" FOREIGN KEY ("tipo_jogo_id") REFERENCES "tb_tipos_jogo" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset nicoletti:1734468468510-11
ALTER TABLE "tb_dezenas" ADD CONSTRAINT "fkgo7xso309ur9g4fkf8v6bx5do" FOREIGN KEY ("aposta_id") REFERENCES "tb_apostas" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset nicoletti:1734468468510-12
ALTER TABLE "tb_dezenas_jogos" ADD CONSTRAINT "fkjhtsewqxmiwvyx17ot9w52hlr" FOREIGN KEY ("jogo_id") REFERENCES "tb_jogos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset nicoletti:1734468468510-13
ALTER TABLE "tb_premios" ADD CONSTRAINT "fkp6od1aq8jjunymsgj4j26qo51" FOREIGN KEY ("jogo_id") REFERENCES "tb_jogos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

